datamodule:
  # must use the absolute path of dataset to work with hydra
  zarr_path: ~/dev/garmentnets/data/garmentnets_dataset.zarr/Dress
  metadata_cache_dir: ~/local/.cache/metadata_cache_dir
  batch_size: 1
  num_workers: 0
  # sample size
  num_pc_sample: 8000
  num_pc_sample_final: 4000
  num_volume_sample: 0
  num_surface_sample: 6000
  num_surface_sample_init: 10000
  # mixed sampling config
  surface_sample_ratio: 0
  surface_sample_std: 0.05
  # surface sample gt-sim points noise
  surface_gt_normal_noise_ratio: 0
  surface_gt_normal_std: 0.01
  # feature config
  use_rgb: True
  use_nocs_as_feature: False
  # voxelization config
  voxel_size: 0.0025
  # data augumentation
  enable_augumentation: False
  enable_zero_center: False
  num_views: 4
  pc_noise_std: 0
  use_pc_nocs_frame1_aug: True
  use_fist_frame_pc_nocs_aug_in_test: True
  pc_nocs_global_scale_aug_range: [0.8, 1.2]
  pc_nocs_global_max_offset_aug: 0.1
  pc_nocs_gaussian_std: 0.05
  use_mesh_nocs_aug: True
  use_fist_frame_mesh_nocs_aug_in_test: True
  mesh_nocs_global_scale_aug_range: [0.8, 1.2]
  mesh_nocs_global_max_offset_aug: 0
  # random seed
  static_epoch_seed: False
  # datamodule config
  dataset_split: [8,1,1]
  split_seed: 0
  remove_invalid_interval_in_train: False
  # first-frame fitting config
  alpha: 1000.0
  finetune_offset: [0., -0.03, 0.]

main:
  garmentnets_prediction_output_dir: ~/dev/garmentnets/outputs/2021-07-31/01-43-33
  checkpoint_path: ~/dev/garmentnets/data/garmentnets_checkpoints/pipeline_checkpoints/Dress_pipeline.ckpt
  gpu_id: 0
prediction:
  # val or test
  subset: test
  volume_size: 128
  max_refine_mesh_step: 1
  use_valid_grip_interval: True
  use_cross_interval_tracking: True
  use_garmentnets_prediction: False
  disable_mesh_nocs_refine_in_test: False
  disable_pc_nocs_refine_in_test: False
  alpha: 1000.0
  value_threshold: 0.128
  debug: False
logger:
  mode: offline
  name: null
  tags: []
